### ISSUE TITLE
library not found for -lPods-AFNetworking

### ISSUE THREAD

**Issue by guoxuhui** [TuWei1992/NutzCommunity#5]
pod install 若出现 ld: library not found for -lPods-AFNetworking 类似的， 设置 Project -> Pods 的 Build Active Architecture Only 为 NO

按照这个设置貌似还是不行

**Comment by guoxuhui** [comment]
找到问题了，需要Podfile文件升级一下

platform :ios, '7.0'
inhibit_all_warnings!
use_frameworks!

def pods
	pod 'AFNetworking', '2.6.3'
	pod 'NYXImagesKit', '~> 2.3'
	pod 'BlocksKit', '~> 2.2.0'
	pod 'RegexKitLite', '~> 4.0'
	pod 'MBProgressHUD', '~> 0.8'
	pod 'SDWebImage' , '3.7.3'
	pod 'ReactiveCocoa', '2.4.7'
	pod 'RESideMenu'
	pod 'LGSideMenuController'
	#pod 'GPUImage'
	pod 'Masonry'
	pod 'JDStatusBarNotification'
	pod 'Mantle'
	pod 'JSONModel'
	pod 'GHMarkdownParser'
	pod 'LGPlusButtonsView'
	pod 'FMDB'
	pod 'FMDBHelper'
	pod 'JSBadgeView'
	pod 'DZNEmptyDataSet'
	pod 'ODRefreshControl'
	pod 'FrameAccessor'
  post_install do |installer_representation|
      installer_representation.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['ARCHS'] = 'armv7 arm64'
          end
      end
  end
end

target "Nutz社区" do
  pods
end

**Comment by TuWei1992** [comment]
@hanyi366 我这边没问题啊
